### ISSUE TITLE
Function `model.predictor.prepare_outputs` lacks 1 return output

### ISSUE THREAD

**Issue by LutaoChu** [ThierryDeruyttere/Talk2Car-Destination#5]
No `scale_ind_agg` return
```
Traceback (most recent call last):
  File "test.py", line 355, in <module>
    main(args)
  File "/home/lutaochu/miniconda3/envs/talk2car/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 160, in main
    mu, sigma, pi, scale_ind_agg = model.predictor.prepare_outputs(mu, sigma, pi, location)
ValueError: not enough values to unpack (expected 4, got 3)
```
Please take a look

**Comment by ThierryDeruyttere** [comment]
Thanks for your issue! the variable `scale_ind_agg` is something that remained after we did some tests to know which layer contributed the most to the predictions. We deleted it from the other code but forgot to remove it from test.py. Apologies for this. I pushed a new version. Please fetch the new code! Let me know if something else is still not working out

**Comment by LutaoChu** [comment]
Thx for the quick response!

**Comment by LutaoChu** [comment]
I still encounter errors when running test.py.
First, there is no `gt_referred_obj_top` in testset json. So I change `split` from test to val.
```
        data_test = Talk2Car_Detector(
            split="val", # test set no "gt_referred_obj_top"
```
but encounter the following error
```
Traceback (most recent call last):
  File "/home/lutaochu/miniconda3/envs/talk2car/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lutaochu/miniconda3/envs/talk2car/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lutaochu/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/lutaochu/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/lutaochu/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/lutaochu/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/lutaochu/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/lutaochu/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "Talk2Car-Destination/baselines/PDPC/test.py", line 355, in <module>
    main(args)
  File "/home/lutaochu/miniconda3/envs/talk2car/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "Talk2Car-Destination/baselines/PDPC/test.py", line 243, in main
    bidx
  File "Talk2Car-Destination/baselines/PDPC/talk2car.py", line 189, in get_obj_info
    "rotated_" + item[0]["frame_data_url"].split("/")[-1],
KeyError: 0
```

my script
```
python test.py\
 --gpu_index 0 \
 --data_dir "../../data"\
 --dataset "Talk2Car_Detector"\
 --draw\
 --num_heatmaps_drawn 30\
 --component_topk -1 \
 --checkpoint_path "checkpoint/PDPC_Talk2Car_Detector_use_ref_obj_True_lr_3e-05_bs_32_epochs_100_height_192_width_288_sigma_decay_0.0_pi_entropy_0.0_n_conv_5_combine_at_2_active_scale_inds_[1,1,1,1]_inner_channel32.ckpt"
```
Can you help me run through test.py?

**Comment by ThierryDeruyttere** [comment]
I'm pushing a new update to the repository later today with checkpoints and some updates to requirements.txt and to the dataset

**Comment by ThierryDeruyttere** [comment]
I have pushed the update to the repository. Please read the new [README.md](https://github.com/ThierryDeruyttere/Talk2Car-Destination/blob/master/README.md) and the checkpoints can be found [here](https://github.com/ThierryDeruyttere/Talk2Car-Destination/blob/master/baselines/README.md). Hope this helps.
I've also updated the requirements.txt file
